// dsh (DeepSeek Harness) adapter tests: zstd multi-frame handling, session
// event normalization, and the API surface over the fixture sessions
// (test/fixtures/home/.dsh/sessions — one plain JSONL log, one multi-frame
// .jsonl.zstd log generated by scripts using Node's zstd with checksums).

const { describe, it, before, after } = require('node:test');
const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
const zlib = require('node:zlib');

const dsh = require(path.join(__dirname, '..', 'lib', 'platforms', 'dsh'));
const { startServer, getJson } = require('./helpers.js');

const DSH_PLAIN = 'dsh-fixture-session-0001';
const DSH_ZSTD = 'dsh-fixture-session-0002';

const ZSTD_OPTS = { params: { [zlib.constants.ZSTD_c_checksumFlag]: 1 } };
const frame = (text) => zlib.zstdCompressSync(Buffer.from(text, 'utf8'), ZSTD_OPTS);

// --- zstd multi-frame handling (lib/platforms/dsh) ---

test('scanZstdFrames finds every concatenated frame boundary', () => {
  const frames = [frame('{"a":1}\n'), frame('{"b":2}\n{"c":3}\n'), frame('{"d":4}\n')];
  const buf = Buffer.concat(frames);
  const scan = dsh.scanZstdFrames(buf);
  assert.equal(scan.tornStart, null);
  assert.equal(scan.frames.length, 3);
  let offset = 0;
  for (let i = 0; i < frames.length; i++) {
    assert.equal(scan.frames[i].start, offset);
    offset += frames[i].length;
    assert.equal(scan.frames[i].end, offset);
  }
});

test('decompressDshLog restores all frames where one-shot decompression stops at the first', () => {
  const buf = Buffer.concat([frame('{"a":1}\n'), frame('{"b":2}\n'), frame('{"c":3}\n')]);
  // The trap this adapter exists for: Node's one-shot API reads one frame only.
  const naive = zlib.zstdDecompressSync(buf).toString('utf8');
  assert.equal(naive, '{"a":1}\n');
  assert.equal(dsh.decompressDshLog(buf), '{"a":1}\n{"b":2}\n{"c":3}\n');
});

test('decompressDshLog tolerates a torn trailing frame (crash residue)', () => {
  const full = Buffer.concat([frame('{"a":1}\n'), frame('{"b":2}\n')]);
  const torn = full.subarray(0, full.length - 4); // cut into the last frame's checksum
  const scan = dsh.scanZstdFrames(torn);
  assert.equal(scan.frames.length, 1);
  assert.equal(typeof scan.tornStart, 'number');
  assert.equal(dsh.decompressDshLog(torn), '{"a":1}\n');
});

test('decompressDshLog skips skippable frames', () => {
  const skippable = Buffer.alloc(8 + 3);
  skippable.writeUInt32LE(0x184d2a50, 0);
  skippable.writeUInt32LE(3, 4);
  const buf = Buffer.concat([frame('{"a":1}\n'), skippable, frame('{"b":2}\n')]);
  assert.equal(dsh.decompressDshLog(buf), '{"a":1}\n{"b":2}\n');
});

// --- event normalization ---

test('normalizeDshEvents pairs tool/call with tool/result and parses arguments', () => {
  const lines = [
    JSON.stringify({
      type: 'tool/call',
      seq: 1,
      time: 1768471205000,
      data: { turn: 1, step: 1, callId: 'c1', name: 'bash', arguments: '{"command":"ls"}' },
    }),
    JSON.stringify({
      type: 'tool/result',
      seq: 2,
      time: 1768471206000,
      data: {
        turn: 1,
        step: 1,
        message: {
          source: { kind: 'tool', callId: 'c1' },
          content: [{ type: 'tool-result', toolCallId: 'c1', content: [{ type: 'text', text: 'ok' }], isError: false }],
          role: 'user',
          id: 'r1',
        },
      },
      surfaceOp: 'append',
    }),
  ];
  const messages = dsh.normalizeDshEvents(lines);
  assert.deepEqual(
    messages.map((m) => m.role),
    ['toolCall', 'toolResult']
  );
  assert.equal(messages[0].toolCallId, 'c1');
  assert.deepEqual(messages[0].details, { command: 'ls' });
  assert.equal(messages[1].toolCallId, 'c1');
  assert.equal(messages[1].toolName, 'bash'); // attributed via callId pairing
  assert.equal(messages[1].content[0].text, 'ok');
  assert.equal(messages[1].isError, false);
});

test('normalizeDshEvents flags non-completed turn/end and skips chunk rows', () => {
  const lines = [
    JSON.stringify({
      type: 'text-chunks',
      seq0: 1,
      time0: 1,
      data: { turn: 1, step: 1, index: 0, dt: [0, 0, 0], texts: ['a', 'b', 'c'] },
    }),
    JSON.stringify({ type: 'assistant/chunk', seq: 4, time: 2, data: { turn: 1, step: 1, chunk: { type: 'finish' } } }),
    JSON.stringify({ type: 'turn/end', seq: 5, time: 1768471207000, data: { turn: 1, reason: { kind: 'aborted' } } }),
  ];
  const messages = dsh.normalizeDshEvents(lines);
  assert.equal(messages.length, 1);
  assert.equal(messages[0].role, 'error');
  assert.equal(messages[0].isError, true);
  assert.ok(messages[0].content[0].text.includes('aborted'));
});

test('normalizeDshEvents honors surfaceOp replace (compaction): masked messages are not rendered twice', () => {
  const user = (seq, surfaceOp, text) =>
    JSON.stringify({
      type: 'user/message',
      seq,
      time: 1768471200000 + seq,
      data: { content: [{ type: 'text', text }], source: { kind: 'user' }, role: 'user', id: `u${seq}` },
      surfaceOp,
    });
  const lines = [
    user(1, 'append', 'first'),
    user(2, 'append', 'second'),
    // Compaction summary replaces surface positions [0, 2)
    user(3, { op: 'replace', start: 0, end: 2 }, 'compaction summary'),
    user(4, 'append', 'third'),
  ];
  const texts = dsh.normalizeDshEvents(lines).map((m) => m.content[0].text);
  assert.deepEqual(texts, ['compaction summary', 'third']);
});

test('parseDshSessionFile rejects unsupported format versions', async () => {
  const fsp = require('node:fs/promises');
  const os = require('node:os');
  const tmp = await fsp.mkdtemp(path.join(os.tmpdir(), 'dsh-ver-'));
  const file = path.join(tmp, 'session.jsonl');
  await fsp.writeFile(file, `${JSON.stringify({ type: 'session', version: 1, id: 'x', createdAt: 0 })}\n`);
  await assert.rejects(() => dsh.parseDshSessionFile(file), /Unsupported dsh session format version 1/);
  await fsp.rm(tmp, { recursive: true, force: true });
});

// --- API surface over the fixtures ---

describe('sessions: dsh', () => {
  let srv;
  before(async () => {
    srv = await startServer();
  });
  after(async () => {
    await srv.stop();
  });

  it('lists plain and zstd sessions newest-first with metadata and title', async () => {
    const sessions = await getJson(srv.base, '/api/dsh/sessions');
    assert.equal(sessions.length, 2);
    assert.deepEqual(
      sessions.map((s) => s.id),
      [DSH_ZSTD, DSH_PLAIN]
    );
    const plain = sessions[1];
    assert.equal(plain.timestamp, '2026-01-15T10:00:00.000Z');
    assert.equal(plain.cwd, '/fixtures/project-delta');
    assert.equal(plain.userCount, 1);
    assert.equal(plain.assistantCount, 1);
    assert.equal(plain.toolCallCount, 1);
    assert.equal(plain.toolResultCount, 1);
    assert.ok(plain.firstUserMessage.startsWith('fixture: dsh-needle-delta'));
    assert.deepEqual(plain.topTools, [{ name: 'run_command', count: 1 }]);
    assert.equal(plain.file, 'session.jsonl');

    const zstd = sessions[0];
    assert.equal(zstd.file, 'session.jsonl.zstd');
    assert.equal(zstd.cwd, '/fixtures/project-epsilon');
    // Metadata comes from frames beyond the first: proves multi-frame decoding
    assert.equal(zstd.userCount, 1);
    assert.equal(zstd.assistantCount, 1);
    assert.ok(zstd.firstUserMessage.startsWith('fixture: dsh-zstd-needle-epsilon'));
  });

  it('serves a plain session detail with normalized roles and paired tool calls', async () => {
    const { session, messages } = await getJson(srv.base, `/api/dsh/sessions/${DSH_PLAIN}`);
    assert.equal(session.id, DSH_PLAIN);
    assert.equal(session.cwd, '/fixtures/project-delta');
    assert.equal(session.model, 'deepseek-v4');
    const roles = messages.map((m) => m.role);
    for (const role of ['user', 'reasoning', 'assistant', 'toolCall', 'toolResult']) {
      assert.ok(roles.includes(role), `missing role ${role}`);
    }
    const assistant = messages.find((m) => m.role === 'assistant');
    assert.deepEqual(assistant.usage, { input: 120, output: 40, cacheRead: 80, reasoning: 10 });
    const call = messages.find((m) => m.role === 'toolCall');
    assert.equal(call.toolName, 'run_command');
    assert.equal(call.toolCallId, 'call-dsh-1');
    assert.deepEqual(call.details, { command: 'echo delta' });
    const result = messages.find((m) => m.role === 'toolResult');
    assert.equal(result.toolCallId, 'call-dsh-1');
    assert.equal(result.toolName, 'run_command');
    assert.equal(result.isError, false);
    assert.equal(result.content[0].text, 'delta\n');
  });

  it('fully restores a multi-frame zstd session, including the aborted-turn marker', async () => {
    const { session, messages } = await getJson(srv.base, `/api/dsh/sessions/${DSH_ZSTD}`);
    assert.equal(session.id, DSH_ZSTD);
    const user = messages.find((m) => m.role === 'user');
    assert.ok(user.content[0].text.includes('dsh-zstd-needle-epsilon'));
    const assistant = messages.find((m) => m.role === 'assistant');
    assert.equal(assistant.content[0].text, 'fixture: two frames decoded.');
    // turn/end reason.kind = 'aborted' surfaces as an error marker
    const marker = messages.find((m) => m.role === 'error');
    assert.ok(marker, 'expected an aborted-turn marker');
    assert.equal(marker.isError, true);
    assert.ok(marker.content[0].text.includes('aborted'));
  });

  it('finds dsh sessions via full-text search, including inside zstd logs', async () => {
    const plain = await getJson(srv.base, '/api/search?q=dsh-needle-delta&platform=dsh');
    assert.equal(plain.length, 1);
    assert.equal(plain[0].sessionId, DSH_PLAIN);
    assert.equal(plain[0].platform, 'dsh');
    assert.ok(plain[0].matches[0].snippet.includes('dsh-needle-delta'));

    const zstd = await getJson(srv.base, '/api/search?q=dsh-zstd-needle-epsilon&platform=dsh');
    assert.equal(zstd.length, 1);
    assert.equal(zstd[0].sessionId, DSH_ZSTD);
  });

  it('extracts dsh prompts grouped by cwd', async () => {
    const data = await getJson(srv.base, '/api/prompts?platform=dsh');
    assert.equal(data.totalSessions, 2);
    assert.equal(data.totalPrompts, 2);
    const dirs = data.groups.map((g) => g.directory).sort();
    assert.deepEqual(dirs, ['/fixtures/project-delta', '/fixtures/project-epsilon']);
  });

  it('aggregates dsh tool usage in the tools audit', async () => {
    const audit = await getJson(srv.base, '/api/tools/audit?platform=dsh');
    const run = audit.tools.find((t) => t.name === 'run_command');
    assert.ok(run, 'expected run_command row');
    assert.deepEqual(run.platforms, ['dsh']);
    assert.equal(run.calls, 1);
    assert.equal(run.errors, 0);
    assert.equal(run.avgMs, 2000); // 10:00:05 call → 10:00:07 result
  });

  it('exports a dsh session as OTLP', async () => {
    const payload = await getJson(srv.base, `/api/otlp/dsh/${DSH_PLAIN}`);
    const spans = payload.resourceSpans[0].scopeSpans[0].spans;
    assert.ok(spans.some((s) => s.name === 'execute_tool run_command'));
  });
});
