// Demo-mode API router: answers the REST surface of server.js from bundled
// synthetic fixtures (frontend/src/demo/fixtures.json — generated by
// scripts/build-demo-fixtures.mjs, which runs the real backend over the
// sample logs in frontend/demo/sample-logs, so shapes match exactly).
//
// Served for claude-code / codex / omp: session list + detail, spawned
// sub-agent children (omp), insights, prompts, global search (multi-keyword
// AND over fixture transcripts) and the preloaded prompt library. All
// mutating requests are rejected — the demo is read-only.

import type {
  ChildAgentSummary,
  Insights,
  LibraryData,
  PromptsData,
  SearchResult,
  SessionDetail,
  SessionSummary,
  SpawnLink,
} from '@/api/types';
import fixtures from './fixtures.json';

interface DemoFixtures {
  sessions: Record<string, SessionSummary[]>;
  details: Record<string, SessionDetail>;
  children: Record<string, ChildAgentSummary[]>;
  childDetails: Record<string, SessionDetail>;
  insights: Record<string, Insights>;
  prompts: Record<string, PromptsData>;
  library: LibraryData;
  spawnMap: SpawnLink[];
}

const data = fixtures as unknown as DemoFixtures;

function emptyInsights(): Insights {
  return {
    totalSessions: 0,
    totalMessages: 0,
    totalToolCalls: 0,
    totalCost: 0,
    errorRate: 0,
    tokenUsage: {},
    toolStats: [],
    errorClusters: [],
    trend: [],
  };
}

function emptyPrompts(platform: string): PromptsData {
  return { platform, totalPrompts: 0, totalSessions: 0, groups: [] };
}

// --- Demo search: same semantics as lib/search.js (multi-keyword AND,
// case-insensitive, snippet ±(40/60) chars around the first keyword hit),
// evaluated over the bundled session transcripts.

function textOfMessage(msg: SessionDetail['messages'][number]): string {
  return (msg.content || [])
    .map((c) => (typeof c.text === 'string' ? c.text : ''))
    .filter(Boolean)
    .join('\n');
}

function extractSnippet(text: string, keyword: string): string {
  const idx = text.toLowerCase().indexOf(keyword);
  if (idx === -1) return '';
  const start = Math.max(0, idx - 40);
  const end = Math.min(text.length, idx + keyword.length + 60);
  return (start > 0 ? '…' : '') + text.slice(start, end).replace(/\s+/g, ' ').trim() + (end < text.length ? '…' : '');
}

function searchFixtures(q: string): SearchResult[] {
  const keywords = q.toLowerCase().split(/\s+/).filter(Boolean);
  if (!keywords.length) return [];
  const results: SearchResult[] = [];
  for (const [key, detail] of Object.entries(data.details)) {
    const slash = key.indexOf('/');
    const platform = key.slice(0, slash);
    const sessionId = key.slice(slash + 1);
    const fullText = detail.messages.map(textOfMessage).join('\n').toLowerCase();
    if (!keywords.every((kw) => fullText.includes(kw))) continue;
    const matches: SearchResult['matches'] = [];
    for (const msg of detail.messages) {
      if (matches.length >= 3) break;
      const text = textOfMessage(msg);
      const snippet = extractSnippet(text, keywords[0]);
      if (snippet) matches.push({ role: msg.role, snippet, timestamp: msg.timestamp ?? null });
    }
    if (matches.length) {
      results.push({
        sessionId,
        file: (data.sessions[platform]?.find((s) => s.id === sessionId)?.file as string) || `${sessionId}.jsonl`,
        platform,
        matches,
      });
    }
  }
  return results;
}

export function demoJson<T>(url: string, init?: RequestInit): Promise<T> {
  const method = (init?.method || 'GET').toUpperCase();
  if (method !== 'GET') {
    return Promise.reject(new Error('Demo mode is read-only — run AgentXRay locally for the full experience.'));
  }

  const parsed = new URL(url, 'http://demo.local');
  const parts = parsed.pathname.split('/').filter(Boolean); // ['api', ...]
  const seg = (i: number) => decodeURIComponent(parts[i] || '');
  const ok = (value: unknown) => Promise.resolve(value as T);

  // /api/version — keep the stale-page poller quiet
  if (parsed.pathname === '/api/version') return ok({ bootId: 'demo' });

  // /api/agents and /api/agents/:name/sessions[...] (openclaw — empty in demo)
  if (seg(1) === 'agents') {
    return ok(parts.length === 2 ? [] : []);
  }

  if (parsed.pathname === '/api/insights') {
    const platform = parsed.searchParams.get('platform') || 'openclaw';
    return ok(data.insights[platform] ?? emptyInsights());
  }
  if (parsed.pathname === '/api/prompts') {
    const platform = parsed.searchParams.get('platform') || 'openclaw';
    return ok(data.prompts[platform] ?? emptyPrompts(platform));
  }
  if (parsed.pathname === '/api/prompts/hidden') return ok({ hidden: [] });
  if (parsed.pathname === '/api/search') return ok(searchFixtures(parsed.searchParams.get('q') || ''));
  if (parsed.pathname === '/api/spawn-map') return ok(data.spawnMap ?? []);
  if (seg(1) === 'spawn-tree') return ok({ node: null, parent: null });
  if (parsed.pathname === '/api/library') return ok(data.library ?? { prompts: [] });
  if (parsed.pathname === '/api/library/usage') return ok({ usage: {} });
  if (parsed.pathname === '/api/library/fabric-patterns') return ok({ patterns: [] });
  if (parsed.pathname === '/api/backup/status') {
    return ok({ archiveDir: '(demo)', files: 0, bytes: 0, lastBackup: null });
  }

  // /api/:platform/sessions[/:id[/children[/:name]]]
  if (seg(2) === 'sessions') {
    const platform = seg(1);
    if (parts.length === 3) return ok(data.sessions[platform] ?? []);
    if (parts.length === 4) {
      const detail = data.details[`${platform}/${seg(3)}`];
      if (detail) return ok(detail);
      return Promise.reject(new Error('Session not found in demo data'));
    }
    if (seg(4) === 'children') {
      if (parts.length === 5) return ok(data.children[`${platform}/${seg(3)}`] ?? []);
      const child = data.childDetails[`${platform}/${seg(3)}/${seg(5)}`];
      if (child) return ok(child);
      return Promise.reject(new Error('Child transcript not available in demo'));
    }
  }

  return Promise.reject(new Error('Not available in demo mode'));
}
