// Demo-mode API router: answers the REST surface of server.js from bundled
// synthetic fixtures (frontend/src/demo/fixtures.json — generated by running
// the real backend over hand-written sample logs, so shapes match exactly).
//
// Main path (session list + session detail + insights + prompts) is served for
// claude-code / codex; every other endpoint returns an honest empty result.
// All mutating requests are rejected — the demo is read-only.

import type {
  Insights,
  PromptsData,
  SessionDetail,
  SessionSummary,
} from '@/api/types';
import fixtures from './fixtures.json';

interface DemoFixtures {
  sessions: Record<string, SessionSummary[]>;
  details: Record<string, SessionDetail>;
  insights: Record<string, Insights>;
  prompts: Record<string, PromptsData>;
}

const data = fixtures as unknown as DemoFixtures;

function emptyInsights(): Insights {
  return {
    totalSessions: 0,
    totalMessages: 0,
    totalToolCalls: 0,
    totalCost: 0,
    errorRate: 0,
    tokenUsage: {},
    toolStats: [],
    errorClusters: [],
    trend: [],
  };
}

function emptyPrompts(platform: string): PromptsData {
  return { platform, totalPrompts: 0, totalSessions: 0, groups: [] };
}

export function demoJson<T>(url: string, init?: RequestInit): Promise<T> {
  const method = (init?.method || 'GET').toUpperCase();
  if (method !== 'GET') {
    return Promise.reject(new Error('Demo mode is read-only — run AgentXRay locally for the full experience.'));
  }

  const parsed = new URL(url, 'http://demo.local');
  const parts = parsed.pathname.split('/').filter(Boolean); // ['api', ...]
  const seg = (i: number) => decodeURIComponent(parts[i] || '');
  const ok = (value: unknown) => Promise.resolve(value as T);

  // /api/version — keep the stale-page poller quiet
  if (parsed.pathname === '/api/version') return ok({ bootId: 'demo' });

  // /api/agents and /api/agents/:name/sessions[...] (openclaw — empty in demo)
  if (seg(1) === 'agents') {
    return ok(parts.length === 2 ? [] : []);
  }

  if (parsed.pathname === '/api/insights') {
    const platform = parsed.searchParams.get('platform') || 'openclaw';
    return ok(data.insights[platform] ?? emptyInsights());
  }
  if (parsed.pathname === '/api/prompts') {
    const platform = parsed.searchParams.get('platform') || 'openclaw';
    return ok(data.prompts[platform] ?? emptyPrompts(platform));
  }
  if (parsed.pathname === '/api/prompts/hidden') return ok({ hidden: [] });
  if (parsed.pathname === '/api/search') return ok([]);
  if (parsed.pathname === '/api/spawn-map') return ok([]);
  if (seg(1) === 'spawn-tree') return ok({ node: null, parent: null });
  if (parsed.pathname === '/api/library') return ok({ prompts: [] });
  if (parsed.pathname === '/api/library/usage') return ok({ usage: {} });
  if (parsed.pathname === '/api/library/fabric-patterns') return ok({ patterns: [] });
  if (parsed.pathname === '/api/backup/status') {
    return ok({ archiveDir: '(demo)', files: 0, bytes: 0, lastBackup: null });
  }

  // /api/:platform/sessions[/:id[/children[/:name]]]
  if (seg(2) === 'sessions') {
    const platform = seg(1);
    if (parts.length === 3) return ok(data.sessions[platform] ?? []);
    if (parts.length === 4) {
      const detail = data.details[`${platform}/${seg(3)}`];
      if (detail) return ok(detail);
      return Promise.reject(new Error('Session not found in demo data'));
    }
    if (seg(4) === 'children') {
      if (parts.length === 5) return ok([]);
      return Promise.reject(new Error('Child transcript not available in demo'));
    }
  }

  return Promise.reject(new Error('Not available in demo mode'));
}
